version: '2'

services:
  backend:
    container_name: Transcendence_backend
    build:
      context: ./back-end
    volumes:
      - ./back-end:/home/node/app # copy files
    ports:
      - "8000:8000"
    command: "ls -la"

  database:
    image: "postgres:14"
    restart: always
    env_file:
      - ./back-end/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes: # create volume for postgres
  db:
    driver: local
