version: '2'

services:
  backend:
    container_name: Transcendence_backend
    build:
      context: ./back-end
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/home/node/app # copy files
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: Transcendence_database
    image: "postgres:14"
    restart: always
    env_file:
      - ./back-end/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes: # create volume for postgres
  db:
    driver: local
