version: '2'

services:
  backend:
    image: "node:18" # Latest stable node version
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development # configure node for development environment
    volumes:
      - ./back-end:/home/node/app # copy files
    expose:
      - "8081"
    command: "npm install ; npm run build ; npm start:dev" # install packages and start

  database:
    image: "postgres:14"
    restart: always
    environment:
      - ./back-end/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes: # create volume for postgres
  db:
    driver: local